### PR TITLE
Refactoring and cleanup

### PR DESCRIPTION
**Pull request by astellingwerf**
Hi @aaronpk, love the work you did on this. I've bought a handful of M5StickC Plusses, and use your project as a basis for a slightly different use case. For that reason, I've done a bit of code cleanup and refactoring. I tried to keep it concise, and have explaining commit messages. Let me know if you need any extra information or persuasion to take the PR.

### CODE REVIEW

**Comment by aaronpk** [comment]
This is wonderful, thanks for doing this!

**Comment by Tundrawalker** [comment]
Dude, I will make you a bologna sandwich if you have code on this that will actually compile.

**Comment by Tundrawalker** [comment]
Tried yet again .... AND ..... it compiled and then bricked on reset. haha. compiling other programs brings it back to life. Phew!  I find that the wifi settings cause a conflict with wifi.h  

// Put your wifi SSID and password here
char* ssid = "";
const char* password = "";

I have to remove the first const before char*

then it gets past the error and compiles but bricks  :-(

**Comment by aaronpk** [comment]
It sounds like you might have the issue described in #1

**Comment by osbaldo-ops** [comment]
great job, congratulations.

Will the code update for M5STICKC PLUS be available?

**Pull request merged**
